### ISSUE TITLE
Error staging credentials for corporations;

### ISSUE THREAD

**Issue by WadeBarnes** [bcgov/von-bc-registries-agent#88]
The following error occurs during the `initialization_and_load_tasks / bc_reg_corp_loader / load_and_process_bc_reg_corps / load_bc_reg_data_a` process.  The affected record is not marked with process_success = 'N' so the same record is picked up during subsequent processing cycles, effectively blocking all processing.

```
/data-pipeline/.venv/bin/python3 -u "bcreg/process-corps-generate-creds.py"
Caching data for parties and events ...
Caching data for corporations ...
timestamp out of range: "5483-12-03 00:00:00 BC"
CONTEXT:  converting column "firm_lp_xp_termination_date" for foreign table scan of "corporation", row 997
None
timestamp out of range: "5483-12-03 00:00:00 BC"
CONTEXT:  converting column "firm_lp_xp_termination_date" for foreign table scan of "corporation", row 997
None
Error during caching operation, switching to smaller cache size
Processing: 15.952490074036177
Traceback (most recent call last):
  File "/data-pipeline/bcreg/bcregistries.py", line 624, in get_bcreg_sql
    cursor.execute(sql)
psycopg2.DataError: timestamp out of range: "5483-12-03 00:00:00 BC"
CONTEXT:  converting column "firm_lp_xp_termination_date" for foreign table scan of "corporation", row 997
Traceback (most recent call last):
  File "/data-pipeline/bcreg/eventprocessor.py", line 938, in process_corp_event_queue_internal
    bc_registries.cache_bcreg_corps(specific_corps)
  File "/data-pipeline/bcreg/bcregistries.py", line 524, in cache_bcreg_corps
    self.cache_bcreg_corp_tables(specific_corps, generate_individual_sql)
  File "/data-pipeline/bcreg/bcregistries.py", line 575, in cache_bcreg_corp_tables
    _rows = self.get_bcreg_table(corp_table, corp_num_where, '', True, generate_individual_sql)
  File "/data-pipeline/bcreg/bcregistries.py", line 652, in get_bcreg_table
    return self.get_bcreg_sql(table, sql, cache, generate_individual_sql)
  File "/data-pipeline/bcreg/bcregistries.py", line 624, in get_bcreg_sql
    cursor.execute(sql)
psycopg2.DataError: timestamp out of range: "5483-12-03 00:00:00 BC"
CONTEXT:  converting column "firm_lp_xp_termination_date" for foreign table scan of "corporation", row 997
succeeded,  16 seconds
```

**Comment by WadeBarnes** [comment]
@ianco, while you're at it, could you update the logging to make it easier to track down the exact record causing the error?

**Comment by ianco** [comment]
This error happens during caching, so there's not a specific record we can identify.  (We're doing bulk selects against the database)
